---
title: "Data_cleaning"
output: html_document
---

```{r}
# R setup -graphical analysis.
suppressMessages(library(tidyverse))
suppressMessages(library(ggpubr))
suppressMessages(library(truncnorm))
suppressMessages(library(MASS))
suppressMessages(library(mvtnorm))
suppressMessages(library(coda))
suppressMessages(library(mcsm))
suppressMessages(library(corrplot))
suppressMessages(library(survey))
suppressMessages(library(weights))
suppressMessages(library(mediation))
library(gtools)
ggplot2::theme_set(ggplot2::theme_bw())
```

```{r}
# Final names for our variables
names <- c("Gender","Year_in_school","Frat_or_soro","Binge_drink_5+","Binge_drink_4+",
           "Times_drunk","Describe_habits","Number_of_close_friends","GPA","Marital_status",
           "Hispanic","Race","Religion_raised","HS_drink_freq","HS_drink_usual_quantity",
           "HS_binge","Father_alcohol","Mother_alcohol","Family_attitude_alcohol","Attend_AA",
           "Father_education","Mother_education","Last_drink_when","Drink_problem_mean","Drug_use")
           
```
This file cleans the data and merges them for the final analysis. 
# Survey year: 1993
```{r}
# Directory
data_dir = "/Users/antonio/Dropbox/Duke/Courses_Spring2020/Cases_Studies/Case_3/Case_3/Data/"
# Import the data
data93 =  read_csv(paste(data_dir, "data93.csv", sep = ""))[,-1]
# Start by selecting the variables
subset93 = data93 %>%
  dplyr::select(
    ################ General features
    A1, # Age
    A2, # Gender
    A3, # Year in school - 1 = Freshman, 2= Sophmore, 3 = Junior, 4 = Senior, 5= 5th year, 6= Grad
    A6, # Very important to recode it, with whom do you currently live
    A8, # Greek member
    
    ################ Alchool related variables
    C2, # Binge 5 drinks in last two weeks
    C4, # Binge 4 drinks in last two weeks
    C6, # When last drink - need to recode it
    C9, # 30 days, how many times drunk
    starts_with("C17_"),
    C20, # Current alcohol use
    C8, # 30 days, how many drinks usually
    C7, # Need to use it??
    
    ################ Related Drug variables
    E12A, #Attended AA meetings
    E1_A:E1_J,#Variables of interests - heavy drugs
    
    ################ Education related variables
    F2, # Education satisfaction
    F3, # Number of close friends
    F5, # GPA

    ################ Background variables
    G1, # Current marital status
    G2, # Spanish/Hispanic
    G3, # etnicity - need to fix it
    G4, # Religion raised
    G8:G10, # Alchol in high school
    G11:G13, # Family and alchool
    G14, # father schooling
    G15, # mother schooling
    
    ################ Created variables
    DAYE1A:DAYE1J, 
    
    # Weights
    STWGT_93 
    ) %>%
  mutate(year = 1993)
```
# Survey year: 1997
```{r}
# Import the data
data97 =  read_csv(paste(data_dir, "data97.csv", sep = ""))
subset97 = data97 %>%
  dplyr::select(
    ################ General features
    age = A1, # Age
    gender= A2, # Gender
    year_in_school = A3, # Year in school - 1 = Freshman, 2= Sophmore, 3 = Junior, 4 = Senior, 5= 5th year, 6= Grad
    A8, # Very important to recode it, with whom do you currently live
    greek_member = A9, # Greek member
    ################ Alchool related variables
    "binge_5+" = C1, # Binge 5 drinks in last two weeks
    "binge_4+" = C2), # Binge 4 drinks in last two weeks
    C6, # When last drink - need to recode it
    C9, # 30 days, how many times drunk
    starts_with("C17_"),
    C20, # Current alcohol use
    C8, # 30 days, how many drinks usually
    C7, # Need to use it??
    
    ################ Related Drug variables
    E12A, #Attended AA meetings
    E1_A:E1_J,#Variables of interests - heavy drugs
    
    ################ Education related variables
    F2, # Education satisfaction
    F3, # Number of close friends
    F5, # GPA

    ################ Background variables
    G1, # Current marital status
    G2, # Spanish/Hispanic
    G3, # etnicity - need to fix it
    G4, # Religion raised
    G8:G10, # Alchol in high school
    G11:G13, # Family and alchool
    G14, # father schooling
    G15, # mother schooling
    
    ################ Created variables
    DAYE1A:DAYE1J, 
    
    # Weights
    STWGT_97
    ) %>%
  mutate(year = 1997)
binge5=data97$C1
binge4=data97$C2
currentalc=data97$C5
lastdrink=data97$C10
lastdrink = lastdrink[(lastdrink>2)]
drinkwithin30 = data97$C13
df97=data97[,103:114]
df97[is.na(df97)]=1
df97=as.matrix(df97)
drinkingprob=vector(length=length(df97[,1]),mode="numeric")
for(i in 1:length(df97[,1])){
  drinkingprob[i]=mean(df97[i,1:12])-1
}
AA=data97$E18_A
closefriends=data97$F2
GPA=data97$F4
maritalstatus=data97$G1
latinx=data97$G2
ethnicity=data97$G3
childhoodreligion=data97$G4
hsdrinktimes=data97$G9
hsdrinknumbers=data97$G10
hsbinges=data97$G11
daddrink=data97$G14
momdrink=data97$G15
familydrinking=data97$G16
momcollege=vector(length=length(data97$COLL_ID),mode="numeric")
dadcollege=vector(length=length(data97$COLL_ID),mode="numeric")
for(i in 1:length(data97$COLL_ID)){
  if(data97$G17[i]==3 | data97$G17[i] == 4){
    momcollege[i]=1
  }
  else{
    momcollege[i]=0
  }
  if(data97$G17[i]==2 | data97$G17[i]==4){
    dadcollege[i]=1
  }
  else{
    dadcollege[i]=0
  }
}

```

# Survey year: 1999
```{r}
data99 = read.csv("~/Dropbox/Duke/Courses_Spring2020/Cases_Studies/Case_3/Case_3/Data/data99.csv", header=TRUE)
# Select the following variables
subset99 = data99 %>%
  dplyr::select(
    ################ General features
    A1, # Age
    A2, # Gender
    A3, # Year in school - 1 = Freshman, 2= Sophmore, 3 = Junior, 4 = Senior, 5= 5th year, 6= Grad
    A11, # Greek member
    A10A, # live alone
    A10B, # roommate
    A10C, # live with spouse
    A10D, # live with parents
    
    ################ Alchool related variables
    C1, # Binge 5 drinks in last two weeks
    C2, # Binge 4 drinks in last two weeks
    C6, # Current alcohol use
    C8, # When last drink - need to recode it
    C9, # Alchool in last 30 days
    C10, # 30 days, how many drinks usually
    C11, # 30 days, how many times drunk
    C17A:C17L, # drinking prob: hangover - to - drinking prob: overdose - need to aggregate them 
    
    ################ Related Drug variables
    E17, #Attended AA meetings
    E1A:E1K, #Variables of interests - heavy drugs
    
    ################ Education related variables
    F1, # Education satisfaction
    F2, # Number of close friends
    F4, # GPA
    
    ################ Background variables
    G1, # Current marital status
    G2, # Spanish/Hispanic
    G4, # Religion raised
    G10:G12, # Alchol in high school
    G15:G17, # Family and alchool
    G18, # father schooling
    G19, # mother schooling
    G3A:G3E, # etnicity
    
    ################ Created variables
    DAYE1A:DAYE1K  ,
    
    # Weighs
    STWGT_99
  )%>%
  mutate(year = 1999)
```

Start merging the first two datasets.
```{r}
# Merge general features

# Age gender and year in school
colnames(subset93)[c(1:3)]= c("age", "gender", "year_in_school")
colnames(subset99)[c(1:3)] = c("age", "gender", "year_in_school")
# Greek life
colnames(subset93)[5] = c("greek_member")
colnames(subset99)[4] = c("greek_member")
# Who do you live with
colnames(subset99)[5:8] = c("live_alone","live_roommate","live_spouse","live_parents")
subset93$live_alone = (subset93$A6 == 1)*1
subset93$live_roommate = (subset93$A6 %in% c(2,13,14,15, 17, 18))*1 
subset93$live_spouse = (subset93$A6 %in% c(3,5,7,8, 9, 13, 17,18,20))*1 
subset93$live_parents = (subset93$A6 %in% c(4,8,9,10, 12, 16))*1 
# Drink variables
colnames(subset93)[c(6:7)]= c("binge_5+", "binge_4+")
colnames(subset99)[c(9:10)] = c("binge_5+", "binge_4+")
# Self reported alchol use
colnames(subset93)[colnames(subset93) == "C20"] = "alchol_use"
colnames(subset99)[colnames(subset99) == "C6"]  = "alchol_use"
colnames(subset93)[colnames(subset93) == "C6"] = "last_drink"
colnames(subset99)[colnames(subset99) == "C8"]  = "last_drink"
colnames(subset93)[colnames(subset93) == "C9"] = "30_days_drunk"
colnames(subset99)[colnames(subset99) == "C11"]  = "30_days_drunk"
colnames(subset93)[colnames(subset93) == "C8"] = "30_days_drink_usually"
colnames(subset99)[colnames(subset99) == "C10"]  = "30_days_drink_usually"
colnames(subset93)[colnames(subset93) == "C7"] = "30_days_alchol"
colnames(subset99)[colnames(subset99) == "C9"]  = "30_days_alchol"

# Drinking problems
drinkprobs= c("DP_hangover", "DP_missed_class", "DP_behind_schoolwork",
              "DP_later_regret", "DP_forget_where", "DP_argue_friends", 
              "DP_unpl_sex", "DP_unprot_sex", "DP_damage_property",
              "DP_trouble_police", "DP_hurt", "DP_overdose")

colnames(subset93)[startsWith(colnames(subset93),"C17_") ] = drinkprobs
colnames(subset99)[startsWith(colnames(subset99),"C17")] = drinkprobs

################ Related Drug variables
colnames(subset99)[colnames(subset99) == "E17"] = "AA_meeting"
colnames(subset93)[colnames(subset93) == "E12A"] = "AA_meeting"
drugs = c("Drug_marijuana", "Drug_crack", "Drug_cocaine", "Drug_barbiturates",
          "Drug_amphetamines", "Drug_tranquilizers", "Drug_heroin", 
          "Drug_other_opiates", "Drug_LSD","Drug_PCP", "Drug_ecstasy")
colnames(subset99)[startsWith(colnames(subset99),"E1")] = drugs
colnames(subset93)[startsWith(colnames(subset93),"E1_")] = drugs[-11]
subset93$Drug_ecstasy = 0

################ Education related variables
colnames(subset93)[colnames(subset93) == "F2"] = "Educ_satisfaction"
colnames(subset99)[colnames(subset99) == "F1"] = "Educ_satisfaction"

colnames(subset93)[colnames(subset93) == "F3"] = "N_close_friends"
colnames(subset99)[colnames(subset99) == "F2"] = "N_close_friends"

colnames(subset93)[colnames(subset93) == "F5"] = "GPA"
colnames(subset99)[colnames(subset99) == "F4"] = "GPA"

################ Background variables
colnames(subset93)[colnames(subset93) == "G1"] = "Marital_status"
colnames(subset99)[colnames(subset99) == "G1"] = "Marital_status"

colnames(subset93)[colnames(subset93) == "G2"] = "Spanish"
colnames(subset99)[colnames(subset99) == "G2"] = "Spanish"

colnames(subset93)[colnames(subset93) == "G4"] = "religion"
colnames(subset99)[colnames(subset99) == "G4"] = "religion"

colnames(subset93)[colnames(subset93) == "G4"] = "religion"
colnames(subset99)[colnames(subset99) == "G4"] = "religion"

hghschool = c("HS_times_drank", "HS_n_drinks", "HS_drinks_5+")
colnames(subset93)[colnames(subset93) %in% c("G8","G9","G10")] = hghschool
colnames(subset99)[colnames(subset99) %in% c("G10","G11","G12")] =hghschool

colnames(subset93)[colnames(subset93) == "G14"] = "father_schooling"
colnames(subset99)[colnames(subset99) == "G18"] = "father_schooling"

colnames(subset93)[colnames(subset93) == "G15"] = "mother_schooling"
colnames(subset99)[colnames(subset99) == "G19"] = "mother_schooling"

fam_alchool = c("AlchUse_father", "AlchUse_mother", "AlchUse_famfeel")
colnames(subset93)[colnames(subset93) %in% c("G11", "G12","G13")] = fam_alchool
colnames(subset99)[colnames(subset99) %in% c("G15","G16","G17")] =fam_alchool

race = c("white", "black", "asian", "native_american", "other")
colnames(subset99)[colnames(subset99) %in% c("G3A", "G3B", "G3C", "G3D", "G3E")] =race
subset93$white = (subset93$G3==1)*1
subset93$black = (subset93$G3==2)*1
subset93$asian = (subset93$G3==3)*1
subset93$native_american = (subset93$G3==4)*1
subset93$other = (subset93$G3==5)*1

subset93$DAYE1K = 0

# Weights
colnames(subset93)[colnames(subset93) == "STWGT_93"] = "survey_weight"
colnames(subset99)[colnames(subset99) == "STWGT_99"] = "survey_weight"

# Merge the datasets, keep only the same columns
length(colnames(subset93))  == length(colnames(subset99))
common_cols = Reduce(intersect, list(colnames(subset93), colnames(subset99)))
subset93 = subset93[, colnames(subset93)%in% common_cols]
subset99 = subset99[, colnames(subset99)%in% common_cols]

df = rbind(subset93[,sort(names(subset93))], subset99[,sort(names(subset99))])
write.csv(df, "~/Dropbox/Duke/Courses_Spring2020/Cases_Studies/Case_3/Case_3/Data/data_93_99.csv")
```













