---
title: "Mediation_model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(tidyverse))
suppressMessages(library(ggpubr))
suppressMessages(library(truncnorm))
suppressMessages(library(MASS))
suppressMessages(library(mvtnorm))
suppressMessages(library(coda))
suppressMessages(library(mcsm))
suppressMessages(library(corrplot))
suppressMessages(library(survey))
suppressMessages(library(weights))
suppressMessages(library(mediation))
library(gtools)
ggplot2::theme_set(ggplot2::theme_bw())
```

# Import the data
```{r}
# Import the data
data_dir = "/Users/antonio/Dropbox/Duke/Courses_Spring2020/Cases_Studies/Case_3/Case_3/Data/"
df =  read_csv(paste(data_dir, "data_93_97_99_01.csv", sep = ""))[,-1]
```

# Joe's code
```{r}
# Function to convert Drug_ecstasy into 1's
f <- function(x) {ifelse(x == 0,1,x)}
# Response variable
df$Drug_ecstasy = df$Drug_ecstasy -1
df$Drug_tranquilizers = df$Drug_tranquilizers -1
D <- df %>% dplyr::mutate_at(vars("Drug_ecstasy"),f) %>% dplyr::select(-Drug_marijuana) %>%
  dplyr::select(starts_with("Drug_")) %>% mutate_at(vars(starts_with("Drug_")), function(x){x-1}) %>% mutate(sumVar = rowSums(dplyr::select(., contains("Drug_")))) %>%
  mutate(D = ifelse(sumVar > 0,1,0)) %>% dplyr::select(D)

# Add response variable and drop Drug variables
df = bind_cols(df,D) %>% dplyr::select(-starts_with("Drug_"))
  
# We notice a contraddiciton in the data. The ones that answered queation when did you had 
# last drink and were at level 5 and 4, later declared that they did not drink. This is a measure for
# seriousness in the survey completion, so we drop them.
df = df[-which(df$`30_days_alchol`==1 & df$`30_days_drink_usually`==1),]
df[is.na(df$`30_days_alchol`),]$`30_days_alchol` = 1
df[is.na(df$`30_days_drink_usually`),]$`30_days_drink_usually` = 1
df[is.na(df$`30_days_drunk`),]$`30_days_drunk` = 1

# Recode the variables in DP. If they are NA, then code it as 0. If never had a problem, as 1,
# else as 2.
switch_dp <- function(variable) {
  ifelse(is.na(variable),1,ifelse(variable == 3,2,variable))
}
df = df %>% mutate_at(vars(starts_with("DP_")),switch_dp)

# Get rid of the missing datas in the variables
function_all_na <- function(tibble) {
  which(rowSums(is.na(tibble)) != ncol(tibble))
}
indicies_to_remove <- df %>% dplyr::select(black,white,asian,other,native_american,Spanish) %>% function_all_na
df <- df[indicies_to_remove,]

switch_race <- function(variable) {
  ifelse(is.na(variable),0,variable)
}

df <- df %>% mutate_at(vars(black,Spanish,white,native_american,asian,other), switch_race)
# keep the complete cases
df = df[complete.cases(df), ]
write.csv(df, "/Users/antonio/Dropbox/Duke/Courses_Spring2020/Cases_Studies/Case_3/Case_3/Data/final_data.csv")
df$HS_drinks_5 = df$`HS_drinks_5+` 
############################################################### High school latent factors
M_highschool = ' HS_Drinking  =~ HS_drinks_5 + HS_n_drinks + HS_times_drank
      Parents_Drinkinf  =~ AlchUse_father + AlchUse_mother + AlchUse_famfeel'

# This is how you fit CFA model
fit_highschool = cfa(M_highschool, data=df,ordered = c("HS_drinks_5","HS_n_drinks","HS_times_drank","AlchUse_father","AlchUse_mother","AlchUse_famfeel"))

# Predictions
eta_highschool = lavPredict(fit_highschool) 
############################################################### College drinking factors
# Drinking problem latent variables
M_DP <- 'DP =~ DP_argue_friends + DP_behind_schoolwork + DP_damage_property + DP_forget_where + DP_hangover +
       DP_hurt + DP_later_regret + DP_missed_class + DP_overdose + DP_trouble_police + DP_unpl_sex '
fit_DP = cfa(M_DP, data=df)
eta_DP = lavPredict(fit_DP) 

# College drinking latent variables

M_College <- 'College_drinking =~ 30_days_alchol + 30_days_drink_usually + 30_days_drunk + '
fit_DP = cfa(M_DP, data=df)
eta_DP = lavPredict(fit_DP) 
# Measures

df %>% ggplot(aes(x=HS_drinks_5.,fill=as.factor(D))) + geom_bar() + facet_wrap(~year)
df %>% ggplot(aes(x=HS_times_drank,fill=as.factor(D))) + geom_bar() + facet_wrap(~year)
df %>% ggplot(aes(x=HS_n_drinks,fill=as.factor(D))) + geom_bar() + facet_wrap(~year)


```

```{r}
df <- read.csv("/Users/antonio/Dropbox/Duke/Courses_Spring2020/Cases_Studies/Case_3/Case_3/Data/final_data.csv")
f1 <- function(var) {
  ifelse((var == 3  | var == 5 | var == 6 | var == 7),1,0)
}

df <- df[,-1]
df <- df %>% mutate_at(vars(AlchUse_father,AlchUse_mother, alchol_use),f1)
# 1. 30 days.. questions
# 2. AA_meeting
# 3. age
# 4. Alcohol Use
# 5. Family Variables
# 6. Race
# 7. Binge
# 8. DP
# 9. Education satisfaction
# 10. Father/mother schooling
# 11. Gender
# 12. GPA
# 13. Greek member
# 14/15/16 HS drinking variable
# 17. Live alone, etc.
# 18. Marital Status
# 19. n close friends
# 20. religion
# 21. Year
# 22. Year in school
#


df <- df %>% mutate_at(vars(X30_days_alchol,X30_days_drink_usually,X30_days_drunk,AlchUse_famfeel,
                            "binge_4.","binge_5.",Educ_satisfaction,
                            HS_drinks_5.,HS_n_drinks,HS_times_drank),as.ordered)
df <- df %>% mutate_at(vars(AA_meeting,AlchUse_father,AlchUse_mother,asian,father_schooling,
                            gender,greek_member,starts_with("live_"),starts_with("DP"),Marital_status,mother_schooling,
                       native_american,other,religion,Spanish,white,year,year_in_school,alchol_use),as.factor) %>%
  rename(other_race = other ,age_individ= age)

X <- df %>% dplyr::select(-c("last_drink",starts_with("DAYE1"),"D","survey_weight")) 

# Create y and recode it
y <- df %>% dplyr::select("D")# %>% as.matrix() %>% .[,1]
y <- ifelse(y == 0, -1,1) 
# Model matrix
M = model.matrix(D~., data=cbind(X,y))[,-1]
#da <- list("X"=X,"y"=y)
groups <- c(1,1,1,2,3,4,5,5,5,6,7,7,6,8,8,8,8,8,8,8,8,8,8,8,8,
            9,10,11,12,13,14,15,16,17,17,17,17,18,10,19,6,6,20,6,6,21,
            22)
columns_contrast =colnames(M)
varnames = colnames(X)
groups_contrast = rep(0, ncol(M))
for(n in 1:length(varnames)){
  for(m in 1:length(columns_contrast)){
    if(grepl(varnames[n], columns_contrast[m], fixed=TRUE)){
      print(paste(varnames[n], columns_contrast[m], sep = " - "))
      groups_contrast[m] = groups[n]
    }
  }
}

library(gglasso)
#sampled_rows = sample(c(1:nrow(M)),8000)
#da <- list("X"=M[sampled_rows,],"y"=y[sampled_rows])
da <- list("X"=M,"y"=y)
model_lasso <- cv.gglasso(x=da$X,y=da$y,group=groups_contrast,loss="logit")
model_lasso_simple <- gglasso(x=da$X,y=da$y,group=groups_contrast,loss="logit")
```







